import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Genuine Digital School",
  description: "Generated by Santiago Arce",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
